### ISSUE TITLE
¿Podemos traducir esto al inglés?

### ISSUE THREAD

**Issue by FieryMewtwo** [gatuno/Mancala#1]
Sorry if my Spanish is bad, I mostly only speak English :( I would be happy to help the translation along.

**Comment by gatuno** [comment]
Hey,

Thanks for interesting in this project. But, the network protocol is still broken and pending. The whole thing is i18n, but doing localization is done until later.

What parts do you want to translate?

**Comment by FieryMewtwo** [comment]
I can translate whatever needs done. Mostly, if the user will see it, I want to translate it. Whenever you're ready, you can just send me a direct message on Discord (brodmoran #0272)
(there's a zero before the 272, but GitHub keeps editing it out :(
This looks promising! Keep it up!

(Also, I might not see your comment right away, I'm in Eastern US time. Sorry about that)

Edit:Wow, your English is amazing!
